version: '3.5'
services:
  starcraft: 
    image: desktop-wine:latest
    expose:
      - "5901"
    networks:
      internal:

  novnc:
    image: novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
      - RUN_XTERM=yes
      - RUN_FLUXBOX=yes
    ports:
      - "8080:8080"
    networks:
      internal:

networks:
  internal: