FROM ubuntu-vnc-desktop:latest

RUN export DEBIAN_FRONTEND=noninteractive \
 && apt-get update && apt-get install -y \
    software-properties-common \
    apt-transport-https \
    python-software-properties && rm -rf /var/lib/apt/lists/* 

RUN dpkg --add-architecture i386

RUN wget -qO - https://dl.winehq.org/wine-builds/winehq.key | apt-key add -

RUN apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'

RUN apt-get update && apt-get install -y --install-recommends \
 winehq-stable \
 && rm -rf /var/lib/apt/lists/* 

# Download mono and gecko
RUN mkdir -p /usr/share/wine/mono /usr/share/wine/gecko \
    && wget https://dl.winehq.org/wine/wine-mono/4.9.2/wine-mono-4.9.2.msi \
        -O /usr/share/wine/mono/wine-mono-4.9.2.msi \
    && wget https://dl.winehq.org/wine/wine-gecko/2.47/wine_gecko-2.47-x86.msi \
        -O /usr/share/wine/gecko/wine_gecko-2.47-x86.msi \
    && wget https://dl.winehq.org/wine/wine-gecko/2.47/wine_gecko-2.47-x86_64.msi \
        -O /usr/share/wine/gecko/wine_gecko-2.47-x86_64.msi

# Download winetricks
RUN wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks \
        -O /usr/bin/winetricks \
    && chmod +rx /usr/bin/winetricks

CMD ["/usr/bin/vncserver", "-fg"]