FROM ubuntu:16.04

RUN dpkg --add-architecture i386

RUN export DEBIAN_FRONTEND=noninteractive \
 && apt-get update && apt-get install -y \
    software-properties-common \ 
    python-software-properties \
    apt-transport-https \
    xfce4 \
    wget \ 
    && rm -rf /var/lib/apt/lists/*
    
RUN apt-get purge -y pm-utils xscreensaver*

EXPOSE 5901

RUN wget -qO- https://dl.bintray.com/tigervnc/stable/tigervnc-1.8.0.x86_64.tar.gz | tar xz --strip 1 -C /
RUN wget -nc https://dl.winehq.org/wine-builds/Release.key
RUN apt-key add Release.key
RUN apt-add-repository 'https://dl.winehq.org/wine-builds/ubuntu/'

RUN more /etc/apt/sources.list | grep 'wi'

RUN apt-get update && apt-get install -y --allow-unauthenticated --install-recommends winehq-staging && rm -rf /var/cache/apt/

RUN export uid=1000 gid=1000 && \
mkdir -p /home/developer && \
mkdir -p /etc/sudoers.d && \
echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd && \
echo "developer:x:${uid}:" >> /etc/group && \
echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer && \
chmod 0440 /etc/sudoers.d/developer && \
chown ${uid}:${gid} -R /home/developer

RUN mkdir -p /home/developer/.vnc
RUN echo "password" | vncpasswd -f >> /home/developer/.vnc/passwd
RUN chmod 600 /home/developer/.vnc/passwd

USER developer
ENV HOME /home/developer
WORKDIR /home/developer

RUN mkdir -p /home/developer/install
VOLUME /home/developer/install

EXPOSE 5901

CMD ["/usr/bin/vncserver", "-fg"]